### ISSUE TITLE
TiCDC: The sync-point table got replicated (esp. in bdr-mode)

### ISSUE THREAD

**Issue by kennytm** [pingcap/tiflow#10576]
### What did you do?

1. Create two clusters

    ```sh
    tiup playground v7.6.0 --host 10.0.0.2 --db 1 --kv 1 --pd 1 --ticdc 1 --tiflash 0 --without-monitor
    rm /tmp/tidb-4000.sock
    tiup playground v7.6.0 --host 10.0.0.48 --db 1 --kv 1 --pd 1 --ticdc 1 --tiflash 0 --without-monitor
    ```

2. Setup two changefeeds between them

    ```toml
    # 2to48.toml
    bdr-mode = true
    enable-sync-point = true
    sync-point-interval = "31s"
    ```

    ```toml
    # 48to2.toml
    bdr-mode = true
    enable-sync-point = true
    sync-point-interval = "37s"
    ```

    ```sh
    tiup cdc:v7.6.0 cli changefeed create --pd http://10.0.0.2:2379 --sink-uri mysql://root@10.0.0.48 -c 2to48 --config 2to48.toml
    tiup cdc:v7.6.0 cli changefeed create --pd http://10.0.0.48:2379 --sink-uri mysql://root@10.0.0.2 -c 48to2 --config 48to2.toml
    ```

3. Wait for several minutes (because `minSyncPointInterval` is 30s 🤷)

4. Check the syncpoint tables

    ```sh
    mysql --host 10.0.0.2 --port 4000 -u root -e 'select * from tidb_cdc.syncpoint_v1;'
    mysql --host 10.0.0.2 --port 4000 -u root -e 'select count(*) from tidb_cdc.syncpoint_v1;'

    mysql --host 10.0.0.48 --port 4000 -u root -e 'select * from tidb_cdc.syncpoint_v1;'
    mysql --host 10.0.0.48 --port 4000 -u root -e 'select count(*) from tidb_cdc.syncpoint_v1;'
    ```

### What did you expect to see?

The syncpoint table in 10.0.0.2 only contained entries of the 48to2 changefeed, 
and similarly 10.0.0.48 only contained entries of the 2to48 changefeed.

### What did you see instead?

Both clusters contained sync-point entries from both changefeeds.

### Versions of the cluster

v7.6.0
