### ISSUE TITLE
Config `case-sensitive` does not affect eventFilter.

### ISSUE THREAD

**Issue by asddongmen** [pingcap/tiflow#11570]
### What did you do?

1. create a changefeed with config as fllow:
```toml
case-sensitive = false
[filter]
rules = ['test.t']
[[filter.event-filters]]
matcher = ['test.t'] 
ignore-event = ["delete"] # filter out delete event of table `test.t` 
```
2. Delele a row of  `test.T` in upstream TiDB.

### What did you expect to see?

TiCDC ignores the **DELETE** event. 

### What did you see instead?

TiCDC replicated the **DELETE** event. 

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```
