### ISSUE TITLE
DM to read password from environment

### ISSUE THREAD

**Issue by mzhang77** [pingcap/tiflow#11666]
### Is your feature request related to a problem?

ight now, dm requires storing password in config file:
 
```yaml
## ******** Downstream TiDB instance configuration ********** 
target-database: 
# Configuration of the downstream database instance. 
host: "n.n.n.n" 
port: 4000 
user: "root" 
password: "NElUoZylDevEjgPKvcJdF0Akdn2D"
# If the password is not null, it is recommended to use a password encrypted with dmctl.
```
This is still unsafe. 

### Describe the feature you'd like

DM to read password from environment variable. For example:

```yaml
password: env("DM_PASSWORD")
```

When use it, user need to set the environment variable first:
```shell
export DM_PASSWORD=password
dmctl start-task ... 
```

### Describe alternatives you've considered

There are ways to workaround this security breach, but it's nice if DM can handle it.
