### ISSUE TITLE
False positive configuration check when both shard-mode and TLS configuration are configured

### ISSUE THREAD

**Issue by sunxiaoguang** [pingcap/tiflow#11842]
### What did you do?

When task configuration contains both shard-mode and TLS configuration, start task fails

```yaml
name: "test"
task-mode: all
shard-mode: "pessimistic"
meta-schema: "dm_meta"
ignore-checking-items: ["AUTO_INCREMENT_ID"]

target-database:
  host: "192.168.0.1"
  port: 4000
  user: "root"
  password: "password"

  security:
    ssl-ca: "/path/to/ca.pem"
    ssl-cert: "/path/to/dm.pem"
    ssl-key: "/path/to/dm.key"
```

### What did you expect to see?

Task can start successfully

### What did you see instead?

![Image](https://github.com/user-attachments/assets/e46714dc-0913-4dd6-8ac6-bdfadbc51fe6)

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
Git Commit Hash: 45388394a9b50411b1e15c91e65e476d8aafa928
Git Branch: master
UTC Build Time: 2024-12-06 15:24:40
Go Version: go1.23.2
Failpoint Build: false
```
Upstream MySQL/MariaDB server version:
```console
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v7.1.3-serverless                        |
| Edition: Community                                        |
| Git Commit Hash: 2e8be50b073c26b8979c6988a3888ce57b5cec99 |
| Git Branch: release-7.1-serverless                        |
| UTC Build Time: 2024-11-22 15:30:05                       |
| GoVersion: go1.21.11                                      |
| Race Enabled: false                                       |
| TiKV Min Version: 6.1.0                                   |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
+-----------------------------------------------------------+
```
How did you deploy DM: tiup or manually?
```console
TiUP
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
```
