### ISSUE TITLE
DM: Inconsistency applies to tasks configured with both db and table rules in block-allow-list

### ISSUE THREAD

**Issue by OliverS929** [pingcap/tiflow#11983]
### What did you do?

Specified in config file:

```yaml
block-allow-list:
  bw-rule-1:
    do-tables:
      - db-name: db1
        tbl_name: '*'
      - db-name: db2
        tbl_name: t1
     do-dbs:  [db1]
```

### What did you expect to see?

Expect to see all tables in db1 and t1 in db2 are migrated.

### What did you see instead?

tables in db1 are handled just fine, but t1 in db2 are ignored.

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`): 
```console
8.5
```
Upstream MySQL/MariaDB server version:
```console
8.0
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
8.5
```
How did you deploy DM: tiup or manually?
```console
tiup/manually
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
Finished
```
