### ISSUE TITLE
DM validator does not correctly handle UNSIGNED columns

### ISSUE THREAD

**Issue by kennytm** [pingcap/tiflow#12178]
### What did you do?

1. Create a table both up- and downstream

    ```sql
    create table c (a int unsigned primary key, b tinyint unsigned, c smallint unsigned, d bigint unsigned);
    ```
 
2. <details><summary>Start a task with validation</summary>

    ```yaml
    name: c
    task-mode: incremental
    target-database:
      host: 127.0.0.1
      port: 4000
      user: root
      password: ''
    block-allow-list:
      fr1:
        do-tables:
        - db-name: test
          tbl-name: c
    validators:
      vr1:
        mode: full
        worker-count: 1
        row-error-delay: 1s
    mysql-instances:
    - source-id: a
      block-allow-list: fr1
      validator-config-name: vr1
    ```

    </details>

3. Insert a row which has a high-bit set

    ```sql
    -- upstream
    insert into c values (2233445566, 135, 34567, 9876543210123456789);
    ```

4. Wait for a while
5. Select the downstream result

    ```sql
    -- downstream
    select * from test.c;
    /*
    +------------+------+-------+---------------------+
    | a          | b    | c     | d                   |
    +------------+------+-------+---------------------+
    | 2233445566 |  135 | 34567 | 9876543210123456789 |
    +------------+------+-------+---------------------+
    */
    ```

6. Check the validation result.

### What did you expect to see?

no error.

### What did you see instead?

```json
{
    "result": true,
    "msg": "",
    "error": [
        {
            "id": "1",
            "source": "a",
            "srcTable": "`test`.`c`",
            "srcData": "[-2061521730, -121, -30969, -8570200863586094827]",
            "dstTable": "`test`.`c`",
            "dstData": "[]",
            "errorType": "Expected rows not exist",
            "status": "NewErr",
            "time": "2025-05-20 18:55:32",
            "message": ""
        }
    ]
}
```

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
v9.0.0-beta.1
v8.5.1
```
Upstream MySQL/MariaDB server version:
```console
8.0.33
5.7.36
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
v9.0.0-beta.1
v8.5.1
```
How did you deploy DM: tiup or manually?
```console
irrelevant
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```
