### ISSUE TITLE
better lightning-loader configuration

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#3519]
### Is your feature request related to a problem?

currently DM's config for lightning loader is not well-designed

### Describe the feature you'd like

Regarding the new backend configuration item, I hope it could be optimized.

```
tidb:
  backend: "tidb"
```

1. location
Since this configuration is related to target, I think it can be placed in

```
target-database:
  host: "127.0.0.1"
  port: 4400
  user: "root"
  password: ""
  security:
    ssl-ca: "dir-placeholer/task-ca.pem"
    ssl-cert: "dir-placeholer/dm.pem"
    ssl-key: "dir-placeholer/dm.key"
  import-mode: "${value}"  # If multiple downstreams (N->N) are to be added in the future, this approach can also continue to be used
```

2. the value of the configuration item is not easy to understand, for historical reasons Lightning called tidb and local two modes. We can improve it in dm so that new users can understand it better

- `tidb/local` could be replaced with `logical/physical` or `sql/sst`？,looks better to understand
