### ISSUE TITLE
dm table-routing need support regular expressions

### ISSUE THREAD

**Issue by glkappe** [pingcap/tiflow#4256]
demand:
```
db list: test
table list:
t_1
t_2
t_11
t_12
```
now,table routing need write:
```
routes:
  r1:
    s-p: 'test'
    t-p: 't_[0-9]'
    t-s: 'test'
    t-t: 't'
  r2:
    s-p: 'test'
    t-p: 't_[0-9][0-9]'
    t-s: 'test'
    t-t: 't'
  r3:
    t-s: 'test'
    s-p: 'test'
```

i wish:

```
routes:
  r1:
    s-p: 'test'
    t-p: '~t_*'
    t-s: 'test'
    t-t: 't'
```

include version:
v2.x
v1.x
v5.3.0
