### ISSUE TITLE
some route rules not in effect with lightning-loader 

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/tiflow#4945]
### What did you do?

start a task.yaml with this config

```yaml
---
name: test
task-mode: all
is-sharding: false
meta-schema: "dm_meta"

target-database:
  host: "127.0.0.1"
  port: 3307
  user: "root"
  password: "123456"

mysql-instances:
  - source-id: "mysql-replica-01"
    black-white-list: "instance" # compatible with deprecated config
    mydumper-config-name: "global"
    loader-config-name: "global"
    syncer-config-name: "global"
    route-rules: ["route-rule-1"]

black-white-list: # compatible with deprecated config
  instance:
    do-tables:
      - db-name: "webui"
        tbl-name: "*"

mydumpers:
  global:
    threads: 10
    chunk-filesize: 64
    skip-tz-utc: true
    extra-args: ""

loaders:
  global:
    pool-size: 10
    dir: "./dumped_data"

syncers:
  global:
    worker-count: 16
    batch: 100

routes: # 上游和下游表之间的路由 table routing 规则集
  route-rule-1: # 配置名称
    schema-pattern: "webui" # 库名匹配规则，支持通配符 "*" 和 "?"
    target-schema: "webui_test" # 目标库名称

```

### What did you expect to see?

upstrem db: `webui` should be route to `webui_test`

### What did you see instead?

upstrem db: `webui`  is routed to `webui`

### Versions of the cluster

commit: `9d718dbda0334d0e94f8e3de728b642f52fe3053`

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```
