### ISSUE TITLE
code=46009:class=dm-master:scope=internal:level=medium], Message: sources [mysql-01] have not bound

### ISSUE THREAD

**Issue by truong-hua** [pingcap/tiflow#5402]
### Before asking a question, make sure you have

- [X] Searched existing Stack Overflow questions
- [X] Googled your question
- [X] Searched open and closed [GitHub issues](https://github.com/pingcap/tiflow/issues?q=is%3Aissue)
- [X] Read the [documentation](https://docs.pingcap.com/tidb/stable)

### What is your question?

I'm trying to setup an incremental migration from a Percona (MySQL) to TiDB. The check-test is passed but the start-task give me a result that:

```
{
    "result": false,
    "msg": "[code=46009:class=dm-master:scope=internal:level=medium], Message: sources [mysql-01] have not bound",
    "sources": [
    ]
}
```

This is my source config:

```
# Must be unique.
source-id: "mysql-01"

# Configures whether DM-worker uses the global transaction identifier (GTID) to pull binlogs. To enable this mode, the upstream MySQL must also enable GTID. If the upstream MySQL servi
enable-gtid: true

from:
  host: "percona-xtradb-cluster-gtid"           # e.g.: 172.16.10.81
  user: "root"
  password: "plain_password"   # Supported but not recommended to use a plaintext password. It is recommended to use `dmctl encrypt` to encrypt the plaintext password before using it.
  port: 3306
```

And this is my task config
```
name: task-repl                      # Task name. Must be globally unique.
task-mode: incremental               # Task mode. The "incremental" mode only performs incremental data replication.

# Configures the target TiDB database.
target-database:                     # The target database instance.
  host: "tidb"                    # e.g.: 127.0.0.1
  port: 4000
  user: "root"
  password: "plain_password"            # It is recommended to use `dmctl encrypt` to encrypt the plaintext password before using it.

# Use block and allow lists to specify the tables to be replicated.
block-allow-list:                    # The collection of filtering rules that matches the tables in the source database instance. If the DM version is earlier than v2.0.0-beta.2, use b
  bw-rule-1:                         # The block-allow-list configuration item ID.
    do-dbs: ["mytable"]           # Name of databases to be replicated.

# Configures the data source.
mysql-instances:
  - source-id: "mysql-01"            # Data source ID...i.e., source-id in source1.yaml
    block-allow-list: "bw-rule-1"    # You can use the block-allow-list configuration above.
    # syncer-config-name: "global"    # You can use the syncers incremental data configuration below.
    meta:                            # When task-mode is "incremental" and the target database does not have a checkpoint, DM uses the binlog position as the starting point. If the tar
      binlog-name: "mysql-bin.000008"  # The binlog position recorded in "Step 1. Export all data from MySQL". If the upstream database service is configured to switch master between d
      binlog-pos: 104339215
      binlog-gtid: "8d70bf0c-996d-ee13-72fb-044027090d42:1-977383"
```

This is my dm version
```
/ # /dmctl --version
Release Version: v5.4.0
Git Commit Hash: 14db59be99371a0ef996708fa2867e73b2d7b8af
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-02-13 10:09:51
Go Version: go version go1.16.4 linux/amd64
```
