### ISSUE TITLE
The TiCDC always uses the file to sorter

### ISSUE THREAD

**Issue by phamtai97** [pingcap/tiflow#5580]
### What did you do?

Hi all,
I use the TiCDC to replicate data from TiDB vv5.4.1 cluser to other TiDB v5.4.1 cluster. 
My changefeed config:
```toml
# Specify whether the schema name and table name in this configuration file are case sensitive
# This configuration will affect both filter and sink related configurations, the default is true
case-sensitive = true
 
[filter]
# Transactions with the following StartTs will be ignored
# ignore-txn-start-ts = [1, 2]
 
# The rules of the filter
# Filter rules syntax: https://docs.pingcap.com/tidb/stable/table-filter#syntax
rules = ['*']
 
[mounter]
# the thread number of the the mounter
worker-num = 16
 
[sink]
# For MQ Sinks, you can configure event distribution rules through dispatchers
# Dispatchers support default, ts, rowid and table
# dispatchers = [
#     { matcher = ['test1.*', 'test2.*'], dispatcher = "ts" },
#     { matcher = ['test3.*', 'test4.*'], dispatcher = "rowid" },
# ]
 
# For MQ Sinks, you can configure column selector rules through column-selectors
# column-selectors = [
#     { matcher = ['test1.*', 'test2.*'], columns = ["column1", "column2"] },
#     { matcher = ['test3.*', 'test4.*'], columns = ["!a", "column3"] },
# ]
 
# For MQ Sinks, you can configure the protocol of the messages sending to MQ
# Currently the protocol support open-protocol, canal, canal-json, avro and maxwell.
protocol = "open-protocol"
 
[cyclic-replication]
# Whether to enable cyclic replication
enable = false
 
# The replica ID of this capture
# replica-id = 1
 
# The replica ID should be ignored
# filter-replica-ids = [2, 3]
 
# Whether to replicate DDL
sync-ddl = true
 
[consistent]
# consistent level, none is the default value.
# none: eventual consistent support in non-disaster scenario (should provide a finished-ts)
# eventual: eventual consistent in disaster scenario
level = "none"
 
# file size of single redo log, unit is MB
# max-log-size = 64
 
# interval to flush or upload redo log, default is 1000ms, unit is microseconds
# flush-interval = 1000
 
# storage type for redo log
# nfs: store redo logs in nfs directly
# s3: upload redo logs to s3 storage
# blackhole: used for test only
# storage = "s3://logbucket/test-changefeed?endpoint=http://$S3_ENDPOINT/"
```

And then my cmd:
```sh
cdc cli changefeed create --pd=http://1.2.3.4:1234 \
--sink-uri="mysql://abc:123@1.2.3.4:<1234/?worker-count=16&max-txn-row=2000" \
--changefeed-id="table" --sort-engine="unified" --config=./change_feed.toml
```

Then, I insert data to TiDB v5 cluster. I monitor TiCDC dashboard and see:
<img width="1353" alt="Screen Shot 2022-05-25 at 06 14 28" src="https://user-images.githubusercontent.com/38773351/170146760-b1f67725-c9b4-4828-b105-ecdacfd67d30.png">
<img width="906" alt="Screen Shot 2022-05-25 at 06 14 47" src="https://user-images.githubusercontent.com/38773351/170146783-1b199da6-e04d-4dd1-a201-0af4aebb980e.png">
Althought i use **unified** to sort data, the metric of TiCDC seems to use the file on disk to sort. The memory is used about 200MB. I config the memory for TiCDC that is 64GB. It is large. 

I aslo query changefeed to check the sorter. The result is unified.

Why do TiCDC use the disk to sort while memory is a lot of GB? I expected that the TiCDC has to use memory to sort that has performance. And if the memory is not enough to use, the TiCDC  must use disk.

**Comment by phamtai97** [comment]
@[amyangfei](https://github.com/amyangfei) Can you help me?

**Comment by liuzix** [comment]
How much **free memory** is there on the server?

**Comment by phamtai97** [comment]
[liuzix](https://github.com/liuzix)

**Comment by phamtai97** [comment]
We inserted the data with high TPS. And the TiCDC still uses memory to sort. Then, the memory is not free, it flushes data to disk to sort. Finnaly, we stop inserting data to TiDB and reloading the TiCDC and creating a new changefeed. And the TiCDC always uses the disk to sort.

![image](https://user-images.githubusercontent.com/38773351/170258319-b274e2d1-bb5a-4a46-a2f2-9285a81b369d.png)

**Comment by maxshuang** [comment]
https://asktug.com/t/topic/574381
Will this topic help you?

**Comment by phamtai97** [comment]
@maxshuang  I saw above topic. I have a question: How to config max-memory-percentage to TiCDC? Can update realtime? And does it affect to changefeed task?

**Comment by phamtai97** [comment]
@[maxshuang](https://github.com/maxshuang)

**Comment by maxshuang** [comment]
This phenomenon is expected as (256-64)/256 > 30%.
We have some offical instruction about adjusting the changefeed configuration, but seems the section of `sorter` is miss.
https://docs.pingcap.com/tidb/stable/manage-ticdc#task-configuration-file
We have the planning to offer more inner tuning parameters, but it's not  a high priority.

You can find a vm or container to observe the `max-memory-percentage` behavior, or update the sorter inner parameter as  https://docs.pingcap.com/tidb/stable/manage-ticdc#update-task-configuration

Add following parameters to the configuration file and follow the step of updating changefeed config.
```toml
[sorter]
num-concurrent-worker = xxx
max-memory-consumption = xxx
max-memory-percentage = xxx
```

Have Fun!
