### ISSUE TITLE
start-task/check-task blocked and printed few logs

### ISSUE THREAD

**Issue by buchuitoudegou** [pingcap/tiflow#5759]
### What did you do?

https://asktug.com/t/topic/692986

- check-task automatically before running

### What did you expect to see?

check-task successfully and start to run.

### What did you see instead?

dmmaster was blocked for long without response

### Versions of the cluster

6.0.0

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by buchuitoudegou** [comment]
This problem is not rare. Another report remains open: https://asktug.com/t/topic/663172/17. The potential reason is supposed to be either:
1. the checking SQL is blocked or done soooooo sluggish
2. too many tables but merely few dumper's threads (no likely though, some users increased this configuration but hardly had improvement; others only migrate dozens of tables, which should impossibly be blamed.)

I think the least thing we should do is printing more logs (e.g. record the table that is checking or has been done by log when the log-level is `DEBUG`). Currently, it's intractable to probe the blocking cause.

**Comment by lance6716** [comment]
You can try to reproduce it. Maybe not very hard to reproduce.

**Comment by lance6716** [comment]
https://github.com/pingcap/tiflow/blob/d088785f527d76da78a2a2f11a8c781dcf0a18d0/dm/pkg/checker/table_structure.go#L459

I suspect we should not return nil. In this case no one is reading from `inCh` and `dispatchTableItem` will be blocked

**Comment by lance6716** [comment]
BTW 30m timeout is unacceptable

https://github.com/pingcap/tiflow/blob/d088785f527d76da78a2a2f11a8c781dcf0a18d0/dm/checker/checker.go#L57

**Comment by buchuitoudegou** [comment]
So this check should've been failed but return no errors...I'll try to reproduce it tomorrow...

**Comment by buchuitoudegou** [comment]
> Where is this log? Does it have other clue to identify the problem?

similar with `checkShardingTable`

https://github.com/pingcap/tiflow/blob/d088785f527d76da78a2a2f11a8c781dcf0a18d0/dm/pkg/checker/table_structure.go#L210

`checkTable` routine might exit when error occurs but `inCh` remains open before dispatching all the tables.

**Comment by buchuitoudegou** [comment]
> Where is this log? Does it have other clue to identify the problem?

https://github.com/pingcap/tiflow/blob/d088785f527d76da78a2a2f11a8c781dcf0a18d0/dm/pkg/checker/table_structure.go#L135

**Comment by lance6716** [comment]
problem of `ShardingTablesChecker`

```
MySQL [(none)]> create database tug;
Query OK, 1 row affected (0.039 sec)

MySQL [(none)]> use tug
Database changed
MySQL [tug]> create table t1(c int primary key);
Query OK, 0 rows affected (0.049 sec)

MySQL [tug]> create table t2(c int primary key, c2 int);
Query OK, 0 rows affected (0.049 sec)

MySQL [tug]> create table t3(c int primary key, c3 int);
Query OK, 0 rows affected (0.047 sec)

MySQL [tug]> create table t4(c int primary key, c4 int);
Query OK, 0 rows affected (0.045 sec)

MySQL [tug]> create table t5(c int primary key, c5 int);
Query OK, 0 rows affected (0.046 sec)

MySQL [tug]> create table t6(c int primary key, c6 int);
Query OK, 0 rows affected (0.046 sec)

```

```yaml
name: test             # 任务名称，需要全局唯一
task-mode: all         # 任务模式，可设为 "full"、"incremental"、"all"
shard-mode: "pessimistic"

target-database:       # 下游数据库实例配置
  host: "127.0.0.1"
  port: 4000
  user: "root"
  password: ""         # 如果密码不为空，则推荐使用经过 dmctl 加密的密文

## ******** 功能配置集 **********
block-allow-list:        # 上游数据库实例匹配的表的 block-allow-list 过滤规则集，如果 DM 版本 <= v2.0.0-beta.2 则使用 black-white-list
  bw-rule-1:             # 黑白名单配置的名称
    do-dbs: ["tug"] # 迁移哪些库

# ----------- 实例配置 -----------
mysql-instances:
  - source-id: "mysql-01"  # 上游实例或者复制组 ID，参考  的  配置
    block-allow-list:  "bw-rule-1" # 黑白名单配置名称，如果 DM 版本 <= v2.0.0-beta.2 则使用 black-white-list
    route-rules: ["rule1"]
    mydumper-config-name: "global"

routes:
  rule1:
    schema-pattern: "tug"
    table-pattern: "t*"
    target-schema: "tug"
    target-table: "t"

mydumpers:
  global:
    threads: 1
```

```
goroutine 774 [select, 6 minutes]:
github.com/pingcap/tiflow/dm/pkg/checker.dispatchTableItem({0x72313a8, 0xc001a2c480}, 0x66?, 0xc0017aa420)
	/home/lance/go/src/github.com/pingcap/tiflow/dm/pkg/checker/table_structure.go:709 +0x2fc
github.com/pingcap/tiflow/dm/pkg/checker.(*ShardingTablesChecker).Check(0xc0017aa3c0, {0x7231418, 0xc0017aa4e0})
	/home/lance/go/src/github.com/pingcap/tiflow/dm/pkg/checker/table_structure.go:392 +0xea5
github.com/pingcap/tiflow/dm/pkg/checker.Do.func2(0xa, {0x721bc60, 0xc0017aa3c0})
	/home/lance/go/src/github.com/pingcap/tiflow/dm/pkg/checker/real_checker.go:135 +0xe9
created by github.com/pingcap/tiflow/dm/pkg/checker.Do
```
