### ISSUE TITLE
DM silently ignores update row and delete row events when the row doesn't exist on the target

### ISSUE THREAD

**Issue by dveeden** [pingcap/tiflow#6383]
### What did you do?

MySQL 8.0.29 → TiDB 6.1.0 with DM 6.1.0 with GTID.

On MySQL (source):
```
mysql> CREATE TABLE t1 (id int primary key, c1 varchar(255));
Query OK, 0 rows affected (0.09 sec)

mysql> INSERT INTO t1 VALUES (1, 'test 1');
Query OK, 1 row affected (0.02 sec)

mysql> SET sql_log_bin=OFF;
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (2, 'test 2');
Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO t1 VALUES (3, 'test 3');
Query OK, 1 row affected (0.02 sec)

mysql> SET sql_log_bin=ON;
Query OK, 0 rows affected (0.00 sec)

mysql> UPDATE t1 SET c1='test 2 again' WHERE id=2;
Query OK, 1 row affected (0.02 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> DELETE FROM t1 WHERE id=3;
Query OK, 1 row affected (0.02 sec)

mysql> INSERT INTO t1 VALUES (4, 'test 4');
Query OK, 1 row affected (0.01 sec)

mysql> TABLE t1;
+----+--------------+
| id | c1           |
+----+--------------+
|  1 | test 1       |
|  2 | test 2 again |
|  4 | test 4       |
+----+--------------+
3 rows in set (0.00 sec)
```

On TiDB (target)
```
tidb> TABLE t1;
+----+--------+
| id | c1     |
+----+--------+
|  1 | test 1 |
|  4 | test 4 |
+----+--------+
2 rows in set (0.01 sec)
```

### What did you expect to see?

An error (or at least a warning) about the fact that:

- The row with id=2 couldn't be updated
- The row with id=3 couldn't be deleted

### What did you see instead?

DM continueing to replicate data without any warning or error

### Versions of the cluster

MySQL 8.0.29 → TiDB 6.1.0 with DM 6.1.0

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
» query-status demo-mysql8-tidb
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": true,
            "msg": "",
            "sourceStatus": {
                "source": "mysql8",
                "worker": "worker1",
                "result": null,
                "relayStatus": null
            },
            "subTaskStatus": [
                {
                    "name": "demo-mysql8-tidb",
                    "stage": "Running",
                    "unit": "Sync",
                    "result": null,
                    "unresolvedDDLLockID": "",
                    "sync": {
                        "totalEvents": "31",
                        "totalTps": "0",
                        "recentTps": "0",
                        "masterBinlog": "(binlog.000001, 4914)",
                        "masterBinlogGtid": "e7d25aa3-0833-11ed-830d-52ff284f3c30:1-17",
                        "syncerBinlog": "(binlog.000001, 4914)",
                        "syncerBinlogGtid": "e7d25aa3-0833-11ed-830d-52ff284f3c30:1-17",
                        "blockingDDLs": [
                        ],
                        "unresolvedGroups": [
                        ],
                        "synced": true,
                        "binlogType": "remote",
                        "secondsBehindMaster": "0",
                        "blockDDLOwner": "",
                        "conflictMsg": ""
                    }
                }
            ]
        }
    ]
}

```

**Comment by dveeden** [comment]
From the worker logs:
```
[2022/07/20 17:38:52.479 +02:00] [DEBUG] [syncer.go:2119] ["receive binlog event"] [task=demo-mysql8-tidb] [unit="binlog replication"] [header="{\"Timestamp\":1658331532,\"EventType\":33,\"ServerID\":1,\"EventSize\":79,\"LogPos\":5641,\"Flags\":0}"]
[2022/07/20 17:38:52.479 +02:00] [DEBUG] [syncer.go:2119] ["receive binlog event"] [task=demo-mysql8-tidb] [unit="binlog replication"] [header="{\"Timestamp\":1658331532,\"EventType\":2,\"ServerID\":1,\"EventSize\":84,\"LogPos\":5725,\"Flags\":8}"]
[2022/07/20 17:38:52.479 +02:00] [DEBUG] [syncer.go:2119] ["receive binlog event"] [task=demo-mysql8-tidb] [unit="binlog replication"] [header="{\"Timestamp\":1658331532,\"EventType\":19,\"ServerID\":1,\"EventSize\":54,\"LogPos\":5779,\"Flags\":0}"]
[2022/07/20 17:38:52.479 +02:00] [DEBUG] [syncer.go:2119] ["receive binlog event"] [task=demo-mysql8-tidb] [unit="binlog replication"] [header="{\"Timestamp\":1658331532,\"EventType\":31,\"ServerID\":1,\"EventSize\":76,\"LogPos\":5855,\"Flags\":0}"]
[2022/07/20 17:38:52.479 +02:00] [DEBUG] [checkpoint.go:626] ["compare table location whether is newer"] [task=demo-mysql8-tidb] [unit="binlog replication"] [component="remote checkpoint"] [location="position: (binlog.000001, 5855), gtid-set: e7d25aa3-0833-11ed-830d-52ff284f3c30:1-20"] ["old location"="position: (binlog.000001, 5562), gtid-set: e7d25aa3-0833-11ed-830d-52ff284f3c30:1-19"] [cmpGTID=true]
[2022/07/20 17:38:52.479 +02:00] [DEBUG] [syncer.go:2519] [task=demo-mysql8-tidb] [unit="binlog replication"] [event=row] ["source table"=`test`.`t1`] ["target table"=`test`.`t1`] [location="position: (binlog.000001, 5855), gtid-set: e7d25aa3-0833-11ed-830d-52ff284f3c30:1-20"] ["raw event data"="[[2,\"test 2 again  \"],[2,\"test 2 again\"]]"]
[2022/07/20 17:38:52.479 +02:00] [DEBUG] [syncer.go:2119] ["receive binlog event"] [task=demo-mysql8-tidb] [unit="binlog replication"] [header="{\"Timestamp\":1658331532,\"EventType\":16,\"ServerID\":1,\"EventSize\":31,\"LogPos\":5886,\"Flags\":0}"]
[2022/07/20 17:38:52.479 +02:00] [DEBUG] [checkpoint.go:501] ["save table checkpoint"] [task=demo-mysql8-tidb] [unit="binlog replication"] [component="remote checkpoint"] [location="position: (binlog.000001, 5886), gtid-set: e7d25aa3-0833-11ed-830d-52ff284f3c30:1-20"] [table=`test`.`t1`]
[2022/07/20 17:38:52.479 +02:00] [DEBUG] [syncer.go:2313] [task=demo-mysql8-tidb] [unit="binlog replication"] [event=XID] ["last location"="position: (binlog.000001, 5725), gtid-set: e7d25aa3-0833-11ed-830d-52ff284f3c30:1-20"] [location="position: (binlog.000001, 5886), gtid-set: e7d25aa3-0833-11ed-830d-52ff284f3c30:1-20"]
[2022/07/20 17:38:52.479 +02:00] [DEBUG] [checkpoint.go:636] ["save global checkpoint"] [task=demo-mysql8-tidb] [unit="binlog replication"] [component="remote checkpoint"] [location="position: (binlog.000001, 5886), gtid-set: e7d25aa3-0833-11ed-830d-52ff284f3c30:1-20"]
[2022/07/20 17:38:52.479 +02:00] [DEBUG] [causality.go:92] ["key for keys"] [task=demo-mysql8-tidb] [unit="binlog replication"] [component=causality] [key=2.id.test.t1] [keys="[2.id.test.t1,2.id.test.t1]"]
[2022/07/20 17:38:52.479 +02:00] [DEBUG] [dml_worker.go:138] ["queue for key"] [task=demo-mysql8-tidb] [unit="binlog replication"] [component=dml_worker] [queue=4] [key=2.id.test.t1]
[2022/07/20 17:38:52.480 +02:00] [DEBUG] [baseconn.go:164] ["execute statement"] [task=demo-mysql8-tidb] [unit="binlog replication"] [query="UPDATE `test`.`t1` SET `id` = ?, `c1` = ? WHERE `id` = ? LIMIT 1"] [argument="[2 test 2 again 2]"]
```

So looks like it prepares the `UPDATE` statement and then when executing checks if it returned with an error, but it then fails to check if the number of rows that it updated is correct.

**Comment by lance6716** [comment]
> The row with id=3 couldn't be deleted

 I think this is OK, the row does not exist anyway.

> The row with id=2 couldn't be updated

This is bad. Downstream doesn't have the old value to be updated, so it will not generate new value. Maybe we should raise error because we know data will be inconsistent. And when in [safe-mode](https://docs.pingcap.com/tidb/stable/tidb-binlog-glossary#safe-mode) we can mute this error. Will discuss with PM later.

**Comment by dveeden** [comment]
To show the MySQL replication behaviour for this situation, I've setup replication with [dbdeployer](https://github.com/datacharmer/dbdeployer/) and run the same SQL:

```
dbdeployer deploy replication 8.0.29 --gtid
```

On the primary:
```
master [localhost:21930] {msandbox} (test) > CREATE TABLE t1 (id int primary key, c1 varchar(255));
Query OK, 0 rows affected (0.19 sec)

master [localhost:21930] {msandbox} (test) > INSERT INTO t1 VALUES (1, 'test 1');
Query OK, 1 row affected (0.04 sec)

master [localhost:21930] {msandbox} (test) > SET sql_log_bin=OFF;
Query OK, 0 rows affected (0.00 sec)

master [localhost:21930] {msandbox} (test) > INSERT INTO t1 VALUES (2, 'test 2');
Query OK, 1 row affected (0.01 sec)

master [localhost:21930] {msandbox} (test) > INSERT INTO t1 VALUES (3, 'test 3');
Query OK, 1 row affected (0.01 sec)

master [localhost:21930] {msandbox} (test) > SET sql_log_bin=ON;
Query OK, 0 rows affected (0.00 sec)

master [localhost:21930] {msandbox} (test) > UPDATE t1 SET c1='test 2 again' WHERE id=2;
Query OK, 1 row affected (0.02 sec)
Rows matched: 1  Changed: 1  Warnings: 0

master [localhost:21930] {msandbox} (test) > DELETE FROM t1 WHERE id=3;
Query OK, 1 row affected (0.02 sec)

master [localhost:21930] {msandbox} (test) > INSERT INTO t1 VALUES (4, 'test 4');
Query OK, 1 row affected (0.02 sec)

master [localhost:21930] {msandbox} (test) > TABLE t1;
+----+--------------+
| id | c1           |
+----+--------------+
|  1 | test 1       |
|  2 | test 2 again |
|  4 | test 4       |
+----+--------------+
3 rows in set (0.00 sec)
```

On the replica:
```
slave1 [localhost:21931] {msandbox} (test) > SHOW SLAVE STATUS\G
*************************** 1. row ***************************
               Slave_IO_State: Waiting for source to send event
                  Master_Host: 127.0.0.1
                  Master_User: rsandbox
                  Master_Port: 21930
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000001
          Read_Master_Log_Pos: 9732
               Relay_Log_File: mysql-relay.000002
                Relay_Log_Pos: 9052
        Relay_Master_Log_File: mysql-bin.000001
             Slave_IO_Running: Yes
            Slave_SQL_Running: No
              Replicate_Do_DB: 
          Replicate_Ignore_DB: 
           Replicate_Do_Table: 
       Replicate_Ignore_Table: 
      Replicate_Wild_Do_Table: 
  Replicate_Wild_Ignore_Table: 
                   Last_Errno: 1032
                   Last_Error: Coordinator stopped because there were error(s) in the worker(s). The most recent failure being: Worker 1 failed executing transaction '00021930-1111-1111-1111-111111111111:36' at master log mysql-bin.000001, end_log_pos 9123. See error log and/or performance_schema.replication_applier_status_by_worker table for more details about this failure or others, if any.
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 8836
              Relay_Log_Space: 10154
              Until_Condition: None
               Until_Log_File: 
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File: 
           Master_SSL_CA_Path: 
              Master_SSL_Cert: 
            Master_SSL_Cipher: 
               Master_SSL_Key: 
        Seconds_Behind_Master: NULL
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error: 
               Last_SQL_Errno: 1032
               Last_SQL_Error: Coordinator stopped because there were error(s) in the worker(s). The most recent failure being: Worker 1 failed executing transaction '00021930-1111-1111-1111-111111111111:36' at master log mysql-bin.000001, end_log_pos 9123. See error log and/or performance_schema.replication_applier_status_by_worker table for more details about this failure or others, if any.
  Replicate_Ignore_Server_Ids: 
             Master_Server_Id: 21930
                  Master_UUID: 00021930-1111-1111-1111-111111111111
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: 
           Master_Retry_Count: 86400
                  Master_Bind: 
      Last_IO_Error_Timestamp: 
     Last_SQL_Error_Timestamp: 220721 10:04:01
               Master_SSL_Crl: 
           Master_SSL_Crlpath: 
           Retrieved_Gtid_Set: 00021930-1111-1111-1111-111111111111:1-38
            Executed_Gtid_Set: 00021930-1111-1111-1111-111111111111:1-35
                Auto_Position: 1
         Replicate_Rewrite_DB: 
                 Channel_Name: 
           Master_TLS_Version: 
       Master_public_key_path: 
        Get_master_public_key: 1
            Network_Namespace: 
1 row in set, 1 warning (0.01 sec)

slave1 [localhost:21931] {msandbox} (test) > SELECT * FROM performance_schema.replication_applier_status_by_worker WHERE LAST_ERROR_NUMBER>0\G
*************************** 1. row ***************************
                                           CHANNEL_NAME: 
                                              WORKER_ID: 1
                                              THREAD_ID: NULL
                                          SERVICE_STATE: OFF
                                      LAST_ERROR_NUMBER: 1032
                                     LAST_ERROR_MESSAGE: Worker 1 failed executing transaction '00021930-1111-1111-1111-111111111111:36' at master log mysql-bin.000001, end_log_pos 9123; Could not execute Update_rows event on table test.t1; Can't find record in 't1', Error_code: 1032; handler error HA_ERR_KEY_NOT_FOUND; the event's master log mysql-bin.000001, end_log_pos 9123
                                   LAST_ERROR_TIMESTAMP: 2022-07-21 10:04:01.461972
                               LAST_APPLIED_TRANSACTION: 00021930-1111-1111-1111-111111111111:35
     LAST_APPLIED_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: 2022-07-21 10:03:32.577551
    LAST_APPLIED_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: 2022-07-21 10:03:32.577551
         LAST_APPLIED_TRANSACTION_START_APPLY_TIMESTAMP: 2022-07-21 10:03:32.582077
           LAST_APPLIED_TRANSACTION_END_APPLY_TIMESTAMP: 2022-07-21 10:03:32.621631
                                   APPLYING_TRANSACTION: 00021930-1111-1111-1111-111111111111:36
         APPLYING_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: 2022-07-21 10:04:01.456708
        APPLYING_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: 2022-07-21 10:04:01.456708
             APPLYING_TRANSACTION_START_APPLY_TIMESTAMP: 2022-07-21 10:04:01.461547
                 LAST_APPLIED_TRANSACTION_RETRIES_COUNT: 0
   LAST_APPLIED_TRANSACTION_LAST_TRANSIENT_ERROR_NUMBER: 0
  LAST_APPLIED_TRANSACTION_LAST_TRANSIENT_ERROR_MESSAGE: 
LAST_APPLIED_TRANSACTION_LAST_TRANSIENT_ERROR_TIMESTAMP: 0000-00-00 00:00:00.000000
                     APPLYING_TRANSACTION_RETRIES_COUNT: 0
       APPLYING_TRANSACTION_LAST_TRANSIENT_ERROR_NUMBER: 0
      APPLYING_TRANSACTION_LAST_TRANSIENT_ERROR_MESSAGE: 
    APPLYING_TRANSACTION_LAST_TRANSIENT_ERROR_TIMESTAMP: 0000-00-00 00:00:00.000000
1 row in set (0.00 sec)

slave1 [localhost:21931] {msandbox} (test) > SET gtid_next='00021930-1111-1111-1111-111111111111:36'; BEGIN; COMMIT; SET gtid_next='automatic';
Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.01 sec)

Query OK, 0 rows affected (0.00 sec)

slave1 [localhost:21931] {msandbox} (test) > START REPLICA;
Query OK, 0 rows affected (0.06 sec)

slave1 [localhost:21931] {msandbox} (test) > SHOW SLAVE STATUS\G
*************************** 1. row ***************************
               Slave_IO_State: Waiting for source to send event
                  Master_Host: 127.0.0.1
                  Master_User: rsandbox
                  Master_Port: 21930
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000001
          Read_Master_Log_Pos: 9732
               Relay_Log_File: mysql-relay.000002
                Relay_Log_Pos: 9052
        Relay_Master_Log_File: mysql-bin.000001
             Slave_IO_Running: Yes
            Slave_SQL_Running: No
              Replicate_Do_DB: 
          Replicate_Ignore_DB: 
           Replicate_Do_Table: 
       Replicate_Ignore_Table: 
      Replicate_Wild_Do_Table: 
  Replicate_Wild_Ignore_Table: 
                   Last_Errno: 1032
                   Last_Error: Coordinator stopped because there were error(s) in the worker(s). The most recent failure being: Worker 1 failed executing transaction '00021930-1111-1111-1111-111111111111:37' at master log mysql-bin.000001, end_log_pos 9412. See error log and/or performance_schema.replication_applier_status_by_worker table for more details about this failure or others, if any.
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 8836
              Relay_Log_Space: 10154
              Until_Condition: None
               Until_Log_File: 
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File: 
           Master_SSL_CA_Path: 
              Master_SSL_Cert: 
            Master_SSL_Cipher: 
               Master_SSL_Key: 
        Seconds_Behind_Master: NULL
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error: 
               Last_SQL_Errno: 1032
               Last_SQL_Error: Coordinator stopped because there were error(s) in the worker(s). The most recent failure being: Worker 1 failed executing transaction '00021930-1111-1111-1111-111111111111:37' at master log mysql-bin.000001, end_log_pos 9412. See error log and/or performance_schema.replication_applier_status_by_worker table for more details about this failure or others, if any.
  Replicate_Ignore_Server_Ids: 
             Master_Server_Id: 21930
                  Master_UUID: 00021930-1111-1111-1111-111111111111
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: 
           Master_Retry_Count: 86400
                  Master_Bind: 
      Last_IO_Error_Timestamp: 
     Last_SQL_Error_Timestamp: 220721 10:06:42
               Master_SSL_Crl: 
           Master_SSL_Crlpath: 
           Retrieved_Gtid_Set: 00021930-1111-1111-1111-111111111111:1-38
            Executed_Gtid_Set: 00021930-1111-1111-1111-111111111111:1-36
                Auto_Position: 1
         Replicate_Rewrite_DB: 
                 Channel_Name: 
           Master_TLS_Version: 
       Master_public_key_path: 
        Get_master_public_key: 1
            Network_Namespace: 
1 row in set, 1 warning (0.00 sec)

slave1 [localhost:21931] {msandbox} (test) > SELECT * FROM performance_schema.replication_applier_status_by_worker WHERE LAST_ERROR_NUMBER>0\G
*************************** 1. row ***************************
                                           CHANNEL_NAME: 
                                              WORKER_ID: 1
                                              THREAD_ID: NULL
                                          SERVICE_STATE: OFF
                                      LAST_ERROR_NUMBER: 1032
                                     LAST_ERROR_MESSAGE: Worker 1 failed executing transaction '00021930-1111-1111-1111-111111111111:37' at master log mysql-bin.000001, end_log_pos 9412; Could not execute Delete_rows event on table test.t1; Can't find record in 't1', Error_code: 1032; handler error HA_ERR_KEY_NOT_FOUND; the event's master log mysql-bin.000001, end_log_pos 9412
                                   LAST_ERROR_TIMESTAMP: 2022-07-21 10:06:42.855717
                               LAST_APPLIED_TRANSACTION: 
     LAST_APPLIED_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: 0000-00-00 00:00:00.000000
    LAST_APPLIED_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: 0000-00-00 00:00:00.000000
         LAST_APPLIED_TRANSACTION_START_APPLY_TIMESTAMP: 0000-00-00 00:00:00.000000
           LAST_APPLIED_TRANSACTION_END_APPLY_TIMESTAMP: 0000-00-00 00:00:00.000000
                                   APPLYING_TRANSACTION: 00021930-1111-1111-1111-111111111111:37
         APPLYING_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP: 2022-07-21 10:04:05.789148
        APPLYING_TRANSACTION_IMMEDIATE_COMMIT_TIMESTAMP: 2022-07-21 10:04:05.789148
             APPLYING_TRANSACTION_START_APPLY_TIMESTAMP: 2022-07-21 10:06:42.855219
                 LAST_APPLIED_TRANSACTION_RETRIES_COUNT: 0
   LAST_APPLIED_TRANSACTION_LAST_TRANSIENT_ERROR_NUMBER: 0
  LAST_APPLIED_TRANSACTION_LAST_TRANSIENT_ERROR_MESSAGE: 
LAST_APPLIED_TRANSACTION_LAST_TRANSIENT_ERROR_TIMESTAMP: 0000-00-00 00:00:00.000000
                     APPLYING_TRANSACTION_RETRIES_COUNT: 0
       APPLYING_TRANSACTION_LAST_TRANSIENT_ERROR_NUMBER: 0
      APPLYING_TRANSACTION_LAST_TRANSIENT_ERROR_MESSAGE: 
    APPLYING_TRANSACTION_LAST_TRANSIENT_ERROR_TIMESTAMP: 0000-00-00 00:00:00.000000
1 row in set (0.00 sec)

slave1 [localhost:21931] {msandbox} (test) > SET gtid_next='00021930-1111-1111-1111-111111111111:37'; BEGIN; COMMIT; SET gtid_next='automatic';
Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.01 sec)

Query OK, 0 rows affected (0.00 sec)

slave1 [localhost:21931] {msandbox} (test) > START REPLICA;
Query OK, 0 rows affected (0.05 sec)

slave1 [localhost:21931] {msandbox} (test) > SHOW SLAVE STATUS\G
*************************** 1. row ***************************
               Slave_IO_State: Waiting for source to send event
                  Master_Host: 127.0.0.1
                  Master_User: rsandbox
                  Master_Port: 21930
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000001
          Read_Master_Log_Pos: 9732
               Relay_Log_File: mysql-relay.000002
                Relay_Log_Pos: 9948
        Relay_Master_Log_File: mysql-bin.000001
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB: 
          Replicate_Ignore_DB: 
           Replicate_Do_Table: 
       Replicate_Ignore_Table: 
      Replicate_Wild_Do_Table: 
  Replicate_Wild_Ignore_Table: 
                   Last_Errno: 0
                   Last_Error: 
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 9732
              Relay_Log_Space: 10154
              Until_Condition: None
               Until_Log_File: 
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File: 
           Master_SSL_CA_Path: 
              Master_SSL_Cert: 
            Master_SSL_Cipher: 
               Master_SSL_Key: 
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error: 
               Last_SQL_Errno: 0
               Last_SQL_Error: 
  Replicate_Ignore_Server_Ids: 
             Master_Server_Id: 21930
                  Master_UUID: 00021930-1111-1111-1111-111111111111
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Replica has read all relay log; waiting for more updates
           Master_Retry_Count: 86400
                  Master_Bind: 
      Last_IO_Error_Timestamp: 
     Last_SQL_Error_Timestamp: 
               Master_SSL_Crl: 
           Master_SSL_Crlpath: 
           Retrieved_Gtid_Set: 00021930-1111-1111-1111-111111111111:1-38
            Executed_Gtid_Set: 00021930-1111-1111-1111-111111111111:1-38
                Auto_Position: 1
         Replicate_Rewrite_DB: 
                 Channel_Name: 
           Master_TLS_Version: 
       Master_public_key_path: 
        Get_master_public_key: 1
            Network_Namespace: 
1 row in set, 1 warning (0.00 sec)

slave1 [localhost:21931] {msandbox} (test) > TABLE t1;
+----+--------+
| id | c1     |
+----+--------+
|  1 | test 1 |
|  4 | test 4 |
+----+--------+
2 rows in set (0.00 sec)
```

Things to notice here:

- Replication stopped twice
- I inserted empty GTIDs to skip the two events that caused replication to stop

For the Update_rows event:
> Worker 1 failed executing transaction '00021930-1111-1111-1111-111111111111:36' at master log mysql-bin.000001, end_log_pos 9123; Could not execute Update_rows event on table test.t1; Can't find record in 't1', Error_code: 1032; handler error HA_ERR_KEY_NOT_FOUND; the event's master log mysql-bin.000001, end_log_pos 9123

For the Delete_rows event:
> Worker 1 failed executing transaction '00021930-1111-1111-1111-111111111111:37' at master log mysql-bin.000001, end_log_pos 9412; Could not execute Delete_rows event on table test.t1; Can't find record in 't1', Error_code: 1032; handler error HA_ERR_KEY_NOT_FOUND; the event's master log mysql-bin.000001, end_log_pos 9412
