### ISSUE TITLE
TiCDC's progress tracker is stuck during table scheduling

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#7089]
### What did you do?

1. start upstream TiDB cluster
<details>

```yaml
global:
  user: "root"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  arch: "amd64"

server_configs:
  tidb:
    performance.txn-total-size-limit: 5368709120

monitored:
  node_exporter_port: 9100
  blackbox_exporter_port: 9115

pd_servers:
  - host: 10.2.6.161
  - host: 10.2.6.253
  - host: 10.2.7.158

tidb_servers:
  - host: 10.2.6.161
  - host: 10.2.6.253
  - host: 10.2.7.158

tikv_servers:
  - host: 10.2.6.161
  - host: 10.2.6.253
  - host: 10.2.7.158

cdc_servers:
  - host: 10.2.6.161
  - host: 10.2.6.253
  - host: 10.2.7.158

monitoring_servers:
  - host: 10.2.6.161
  - host: 10.2.6.253
  - host: 10.2.7.158

grafana_servers:
  - host: 10.2.6.161
  - host: 10.2.6.253
  - host: 10.2.7.158
```
</details>

2. start downstream TiDB cluster
<details>

```yaml
global:
  user: "root"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  arch: "amd64"

server_configs:
  tidb:
    performance.txn-total-size-limit: 5368709120

monitored:
  node_exporter_port: 9100
  blackbox_exporter_port: 9115

pd_servers:
  - host: 10.2.6.96
  - host: 10.2.6.152
  - host: 10.2.6.20

tidb_servers:
  - host: 10.2.6.96
  - host: 10.2.6.152
  - host: 10.2.6.20

tikv_servers:
  - host: 10.2.6.96
  - host: 10.2.6.152
  - host: 10.2.6.20

monitoring_servers:
  - host: 10.2.6.96
  - host: 10.2.6.152
  - host: 10.2.6.20

grafana_servers:
  - host: 10.2.6.96
  - host: 10.2.6.152
  - host: 10.2.6.20
```
</details>
3. create changefeed: `tiup cdc:nightly cli changefeed create --sink-uri="mysql://root@10.2.6.152:4000/" -c "test" --server 10.2.6.161:8300`

4. write some data: `../tools/workload -database-host 10.2.6.253 -database-db-name test -row-count 3000000 -table-count 3 -tps 20000`

5. make a big txn: 
```sql
mysql -h 10.2.6.253 -u root -P 4000 -p
use test;
show tables;
begin;
update sbtest0 set k = k + 1;
update sbtest1 set k = k + 1;
update sbtest2 set k = k + 1;
commit;
```

6. reload two nodes
```shell
tiup cluster reload upstream -N 10.2.6.161:8300 -R cdc
tiup cluster reload upstream -N 10.2.6.253:8300 -R cdc
```

### What did you expect to see?

It works normal and finish the scheduling.

### What did you see instead?

TiCDC gets stuck:
```log
[2022/09/16 12:28:26.792 +08:00] [WARN] [progress_tracker.go:248] ["Close process doesn't return in time, may be stuck"] [tableID=68] [trackingCount=1] [lastMinResolvedTs="{\"Mode\":0,\"Ts\":0,\"BatchID\":18446744073709551615}"]
```

### Versions of the cluster

```log
Release Version: v6.3.0-alpha
Git Commit Hash: f60eb2e38e104519d30b988b68fee3f1c5dd8c07
Git Branch: heads/refs/tags/v6.3.0-alpha
UTC Build Time: 2022-09-15 14:26:14
Go Version: go version go1.19 linux/amd64
Failpoint Build: false
```
