### ISSUE TITLE
"invalid value / unknown config name: dm1" when give empty tls config

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tiflow#7384]
### What did you do?

- start job with target config:
```
target-database:
  host: aaxxxxx
  port: 4000
  user: root
  password: "123456"
  max-allowed-packet: null
  session: {}
  security:
    ssl-ca: ""
    ssl-cert: ""
    ssl-key: ""
    cert-allowed-cn: []
    ssl-ca-bytes: []
    ssl-key-bytes: []
    ssl-cert-bytes: []
    ssl-ca-base64: ""
    ssl-key-base64: ""
    ssl-cert-base64: ""
```
- job fail with "invalid value / unknown config name: dm1"

caused by this line, it returns `nil, nil` on empty tls
https://github.com/pingcap/tiflow/blob/e8961d83dde846bd789f5cb862905993eef99dd8/dm/pkg/conn/basedb.go#L71

### What did you expect to see?

skip tls cert or report tls cert error

### What did you see instead?

empty config

### Versions of the cluster

current master branch

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```
