### ISSUE TITLE
Expression filter: UPDATE filter always return "TRUE" when there are INSERT/DELETE filters for the same table

### ISSUE THREAD

**Issue by kennytm** [pingcap/tiflow#7831]
### What did you do?

0. create and populate the table...

```sql
create table db.tbl (p bigint primary key, v int);
insert into db.tbl values (1, 1), (3, 3);
```

1. prepare a DM task with the following filters

```yaml
expression-filter:
  e11:
    schema: db
    table: tbl
    insert-value-expr: v = 1
  e12:
    schema: db
    table: tbl
    update-old-value-expr: v = 1
    update-new-value-expr: v = 1

mysql-instances:
- expression-filters: ["e11", "e12"]
  ....
```

2. Perform an UPDATE

```sql
update db.tbl set v = 2 where v = 3;
```

### What did you expect to see?

The UPDATE statement should be synchronized since it hits none of the filters

```sql
select * from db.tbl;
```
| p | v |
|---|---|
| 1 | 1 |
| 3 | 2 |

### What did you see instead?

The UPDATE statement is *skipped*

| p | v |
|---|---|
| 1 | 1 |
| 3 | 3 |

(The log indicates the expression "1" is evaluated inside `SkipDMLByExpression`)

### Versions of the cluster

v6.4.0
