### ISSUE TITLE
support gcs scheme in redo log

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#7987]
### Is your feature request related to a problem?

```toml
[consistent] 
level = "eventual"
storage = "gcs://dp-uw1/fubintest/redolog?credentials-file=gcp-qa-dp-testing-dev-36aee7310524.json"
max-log-size = 1 
```
Use the above configuration to create changefeed and meets such error: `[CDC:ErrConsistentStorage]consistent storage (gcs) not support`.

### Describe the feature you'd like

support gcs scheme in redo log
