### ISSUE TITLE
dm: syncer failed to sync remaining dml after shard-ddl is resolved

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tiflow#8253]
### What did you do?

- prepare 2 source: 3306 and 3307
- execute `create database test; use test; create table t(a decimal(20,6)) charset utf8mb4 collate utf8mb4_bin;` on both source
- start dm task, wait it enter sync phase
- on 3306, run: `alter table test.t modify column a decimal(20,2); insert into test.t values(1); insert into test.t values(1);`
- on 3307, run: `alter table test.t modify column a decimal(20,2);`
- `query-status`, no error. `show-ddl-locks` shows ddl is synced
- `select * from test.t;` on downstream, empty result while we expect 2 rows
- on 3306, run `insert into test.t values(1);`
- `select * from test.t;` on downstream, shows 3 rows

task config
```yaml
name: test
task-mode: all
is-sharding: true
shard-mode: optimistic
ignore-checking-items: ["all"]

target-database:
  host: "127.0.0.1"
  port: 4000
  user: "root"
  password: ""

mysql-instances:
  - source-id: "mysql-3306"
    block-allow-list:  "ba-rule1"
    route-rules: ["global"]
    mydumper-config-name: "dump1"
    loader-config-name: "load1"
  - source-id: "mysql-3307"
    block-allow-list:  "ba-rule1"
    route-rules: ["global"]
    mydumper-config-name: "dump2"
    loader-config-name: "load2"

block-allow-list:
  ba-rule1:
    do-dbs: ["test"]
mydumpers:
  dump1:
    mydumper-path: "dumped_data-dump1"
  dump2:
    mydumper-path: "dumped_data-dump2"
loaders:
  load1:
    dir: "loader_load1"
  load2:
    dir: "loader_load2"

routes:
  global:
    schema-pattern: test
    table-pattern: "t*"
    target-schema: test
    target-table: "t"
```

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
6.5.0
```
Upstream MySQL/MariaDB server version:
```console
one 5.7, one 8.0
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
6.1
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```
