### ISSUE TITLE
[Dynamic Regions] CDC changefeed stucks when partitioned-raft-kv = true and enable-table-across-nodes = true 

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9439]
### What did you do?

1. TiDB cluster with partitioned-raft-kv enabled 
```
tikv:
          baseImage: hub-new.pingcap.net/qa/tikv
          config: |
            storage.engine = "partitioned-raft-kv"
            [cdc]
              min-ts-interval = "500ms"
              incremental-scan-threads = 64
              incremental-scan-concurrency = 256
              incremental-scan-speed-limit = "512MiB"
```
2. create cdc kakfa changefeed with enable-table-across-nodes = true
```
/cdc  cli  changefeed  create "--server=127.0.0.1:8301" "--sink-uri=kafka://downstream-kafka.cdc-kafka-scale-big-table-longrun-tps-1860860-1-836:9092/kafka-scale-big-table-realtime?max-message-bytes=1048576&protocol=open-protocol&replication-factor=2" "--changefeed-id=kafka-scale-big-table-realtime" "--config=/tmp/changefeed.toml"

==/tmp/changefeed.tom==
[scheduler]
enable-table-across-nodes = true 
region-threshold = 1_000
```

3. run workload and check cdc lag

### What did you expect to see?

cdc lag should be normal

### What did you see instead?

CDC lag is normal at first, then changefeed stucks.
This issue is seen when partitioned-raft-kv enabled = true (reproduced 2 times out of 2 attempts)
![image](https://github.com/pingcap/tiflow/assets/7403864/908ca63d-19d9-4582-9154-1ae088aac403)
![image](https://github.com/pingcap/tiflow/assets/7403864/7e70720d-485c-4926-9939-b780c4bf4846)

### Versions of the cluster

cdc version:

Release Version: v7.3.0-alpha
Git Commit Hash: 9d6622ed8df1488ffabbdc5a3bbfbf4ce71f3cf0
Git Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time: 2023-07-25 11:03:13
Go Version: go version go1.20.6 linux/amd64
Failpoint Build: false

**Comment by overvenus** [comment]
Is there any metrics or log?

**Comment by overvenus** [comment]
Discussed offline, from metrics, it appears that there are some locks left unresolved. Because TiKV is repeated OOM, it is possible some txn failed without cleaning up locks.

![image](https://github.com/pingcap/tiflow/assets/2150711/d6ca294e-e8cc-4d32-8cae-434e4182e792)

**Comment by fubinzh** [comment]
> Discussed offline, from metrics, it appears that there are some locks left unresolved. Because TiKV is repeated OOM, it is possible some txn failed without cleaning up locks.
> 
> ![image](https://user-images.githubusercontent.com/2150711/257113551-d6ca294e-e8cc-4d32-8cae-434e4182e792.png)

@overvenus do we have issue to track the TiKV OOM problem?

**Comment by fubinzh** [comment]
This issue not seen when retesting the same scenario with 8C 32G TiKV, cdc lag wasnormal and TiKV OOM not happened.
TiKV commit tested: lastest master, b9e5e376252c1760b60a21f47822b7e6510d8434

![image](https://github.com/pingcap/tiflow/assets/7403864/1a1bd79b-4151-4497-b7a6-4bfec9d69680)

![image](https://github.com/pingcap/tiflow/assets/7403864/73e6c3b9-b857-4a80-9466-2087c034c3b6)

```
       tikv:
          baseImage: hub-new.pingcap.net/qa/tikv
          config: |
            storage.engine = "partitioned-raft-kv"
            [cdc]
              min-ts-interval = "500ms"
              incremental-scan-threads = 64
              incremental-scan-concurrency = 256
              incremental-scan-speed-limit = "512MiB"
          limits:
            cpu: 8000m
            memory: 32Gi
            storage: 1400Gi
          maxReplicas: 3
          replicas: 3
          requests:
            cpu: 8000m
            memory: 32Gi
            storage: 1400Gi
          storageClassName: fast-disks
          version: master
```
