### ISSUE TITLE
DM physical parallel import fails with "checksum mismatched, KV number in source files: 99515551, KV number in TiDB cluster: 0"

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9446]
### What did you do?

1. DM downstream with partitioned-raft-kv enabled
```
config: |
            [storage]
              engine = "partitioned-raft-kv"
```
2. prepare data for 2 MySQL upstreams respectively
```
# upstream1
sysbench --db-driver=mysql --mysql-host=upstream1.dm-lighting-physical-backend-big-tps-1746494-1-560 --mysql-port=3306 --mysql-user=root --mysql-db=dm_lightning_physical_backend --tables=10 --table-size=100000000 --create_secondary=off --time=7200 --threads=16 oltp_write_only prepare
# upstream 2
go-ycsb load mysql -P /workloads/workloadd -p recordcount=100000000 -p autocommit=1 -p databasename=test -p tablecount=5 -p mysql.host=upstream2.dm-lighting-physical-backend-big-tps-1746494-1-560 -p mysql.port=3306 --threads=16
```
3. create source and start DM task
```
---
name: dm_lightning_physical_backend
task-mode: all
is-sharding: false
meta-schema: "dm_meta"

loaders:
    global:
        pool-size: 16
        dir: "/var/lib/dm-worker/dumped_data"
        import-mode: "physical" 
        sorting-dir-physical: "/var/lib/dm-worker/dumped_data"
        on-duplicate-physical: "none"
        disk-quota-physical: "0"
        checksum-physical: "required"

target-database:
    host: "downstream-tidb"
    port: 4000
    user: "root"
    password: ""

mysql-instances:
    - source-id: "source-0"
      block-allow-list: "instance"
      loader-config-name: "global"
    - source-id: "source-1"
      block-allow-list: "instance"
      loader-config-name: "global"

block-allow-list:
    instance:
        do-dbs: ["dm_lightning_physical_backend", "test"]

```
4. Wait DM task to be load to downstream via lightning physical backend

### What did you expect to see?

4. data should be loaded to downstream TiDB

### What did you see instead?

One of the task paused due to "checksum mismatched, KV number in source files: 99515551, KV number in TiDB cluster: 0"

```
2023-07-23T09:21:39.145Z        INFO        k8s/dmcluster.go:54        exec on dm result{podName 15 0 dm-dm-master-0 <nil>} {containerName 15 0 dm-master <nil>} {cmd 1 0  [/bin/sh -c /dmctl --master-addr=[127.0.0.1:8261](http://127.0.0.1:8261/) query-status -s source-0 -s source-1 dm_lightning_physical_backend]} {stdout 15 0 {
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": true,
            "msg": "",
            "sourceStatus": {
                "source": "source-0",
                "worker": "dm-dm-worker-2",
                "result": null,
                "relayStatus": null
            },
            "subTaskStatus": [
                {
                    "name": "dm_lightning_physical_backend",
                    "stage": "Running",
                    "unit": "Load",
                    "result": null,
                    "unresolvedDDLLockID": "",
                    "load": {
                        "finishedBytes": "40979895232",
                        "totalBytes": "204899587812",
                        "progress": "20.00 %",
                        "metaBinlog": "(mysql-bin.000177, 788673616)",
                        "metaBinlogGTID": "2dc08313-28fd-11ee-a90a-ca19dd2bbb02:1-375811",
                        "bps": "13531951"
                    },
                    "validation": null
                }
            ]
        },
        {
            "result": true,
            "msg": "",
            "sourceStatus": {
                "source": "source-1",
                "worker": "dm-dm-worker-0",
                "result": null,
                "relayStatus": null
            },
            "subTaskStatus": [
                {
                    "name": "dm_lightning_physical_backend",
                    "stage": "Paused",
                    "unit": "Load",
                    "result": {
                        "isCanceled": false,
                        "errors": [
                            {
                                "ErrCode": 34021,
                                "ErrClass": "load-unit",
                                "ErrScope": "internal",
                                "ErrLevel": "medium",
                                "Message": "checksum mismatched, KV number in source files: 99515551, KV number in TiDB cluster: 0",
                                "RawCause": "",
                                "Workaround": "If TiDB cluster has more KV, please check if the migrated tables are empty before the task. If source files have more KV, please set `on-duplicate-physical` and restart the task to see data duplication. You can resume the task to ignore the error if you want."
                            }
                        ],
                        "detail": null
                    },
                    "unresolvedDDLLockID": "",
                    "load": {
                        "finishedBytes": "105289755465",
                        "totalBytes": "105289755465",
                        "progress": "100.00 %",
                        "metaBinlog": "(mysql-bin.000123, 748828114)",
                        "metaBinlogGTID": "2e0d22ee-28fd-11ee-98ad-063376b16c0a:1-99515553",
                        "bps": "34555475"
                    },
                    "validation": null
                }
            ]
        }
    ]
}
```

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
["Welcome to dm-master"]
 [release-version=v7.3.0-alpha] 
[git-hash=02c6aa9d2d8c256d9177db55f0a3b3138e7ec761]
 [git-branch=heads/refs/tags/v7.3.0-alpha]
 [utc-build-time="2023-07-21 09:40:33"] 
[go-version="go version go1.20.6 linux/amd64"] 
[failpoint-build=false]
```

Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
master
```
How did you deploy DM: tiup or manually?
K8S

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```
