### ISSUE TITLE
dm: support report error when replicate incompatible ddl

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tiflow#9850]
### Is your feature request related to a problem?

Some customers have experienced issues with upstream tools like pt-osc, which truncate the range of values during DDL changes like modifying Varchar(64) to Varchar(32), resulting in data loss. While these DDL changes might only produce warnings, there is a concern that they could execute successfully in TiDB under certain SQL modes and potentially cause downstream failures. It is advisable for DM to intercept and handle these DDL changes proactively. This approach also prevents prolonged scanning of large tables where eventual errors might occur due to data length mismatches.

### Describe the feature you'd like

```
filters:
  rule-1:
    schema-pattern: "*"   # The name of the database for which this binlog event filter should be applied. Use "*" to indicate all databases, as needed by the user.
    table-pattern: "*"    # The name of the table for which this binlog event filter should be applied. Use "*" to indicate all tables, as needed by the user.
    events: ["incompatible_ddl_changes"]  # The binlog events to be parsed. Set to "incompatible_ddl_changes" to represent DDL changes that cause incompatibility and data inconsistency.
    action: error  # The action to be taken when this DDL is encountered. "error" indicates an error should be raised, and synchronization should stop. Other possible values are "ignore" and "do". The default value is "do".

  rule-2:
    schema-pattern: "test1"   # The name of the database for which this binlog event filter should be applied, set to "test1".
    table-pattern: "t*"    # The name of the table for which this binlog event filter should be applied, for tables starting with "t".
    events: ["Modify Column", "Value Range Decrease"]  # Represents the event types to be parsed and blocked. Here, it indicates modifying column types and reducing the value range.
    action: error  # The action to be taken when this DDL is encountered. "error" indicates an error should be raised, and synchronization should stop. Other possible values are "ignore" and "do". The default value is "do".

```
